### ISSUE TITLE
this line on action does not work

### ISSUE THREAD

**Issue by pandey-rjn** [heera-os/archrepo-stable#1]
https://github.com/heera-os/archrepo-stable/blob/83ee700b77682ebc6f12a36ae6a02c0d2ee32de0/action.sh#L74

**Comment by adi-g15** [comment]
![image](https://user-images.githubusercontent.com/37269665/127212934-7abaa24a-fb0e-485c-a4ae-362d9721de72.png)

It was due to qhotkey not found. I may have not pushed it earlier maybe :sweat_smile:
