### ISSUE TITLE
Automatically updating the submodules

### ISSUE THREAD

**Issue by adi-g15** [heera-os/archrepo-stable#2]
Like commit https://github.com/heera-os/archrepo-stable/commit/2b3e2546c757fe1b87fc0ffb4811c698da987349, should we update the submodules to latest commit in the heera-base or similar repos, so no need to do it by self ?
It won't affect the builds, since they use latest tags either way.

Found this action may help: https://github.com/marketplace/actions/submodule-sync

@khumnath ?

**Comment by khumnath** [comment]
I think archrepo should update automatically when we change codes on repos. We can update archrepo-stable manually.
I still learning git submodules.

**Comment by adi-g15** [comment]
> I think archrepo should update automatically when we change codes on repos. We can update archrepo-stable manually.

Ok, will do it in the archrepo :+1:
